version: '3'
networks:
  proxynet:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always 
    networks:
      - proxynet
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=940416
      - POSTGRES_DB=devlog
    volumes:
      - ./devlog_data:/var/lib/postgresql/data

  backend:
    container_name: devlog-api
    build: .
    restart: always
    networks:
      - proxynet
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:db
